spring.application.name=doctor_consult_app
spring.datasource.url=jdbc:postgresql://localhost:5432/doctor_app
spring.datasource.username=postgres
spring.datasource.password=Anand@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true